name: okyydsxiaomai-sync
on:
  schedule:
    - cron: '21 0-23/4 * 8 *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-okyyds-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync okyyds-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/okyyds/duck.git"
          source_branch: "master"
          destination_branch: "okyyds-scripts"
          github_token: ${{ secrets.PAT }}
