name: SuMaiKaDe-sync
on:
  schedule:
    - cron: '11 0-23/4 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-SuMaiKaDe-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync SuMaiKaDe-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/SuMaiKaDe/bot.git"
          source_branch: "maim"
          destination_branch: "SuMaiKaDe-scripts"
          github_token: ${{ secrets.PAT }}
