name: walle1798-sync
on:
  schedule:
    #- cron: '1 6-23/4 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-walle1798-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync walle1798-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/walle1798/WALL.E.git"
          source_branch: "master"
          destination_branch: "walle1798"
          github_token: ${{ secrets.PAT }}
