name: xuanpro-sync
on:
  schedule:
    - cron: '6 5,12,20 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-xuanpro-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync xuanpro-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xuanpro/JD_Diy"
          source_branch: "main"
          destination_branch: "xuanpro-JD_diy"
          github_token: ${{ secrets.PAT }}
